### ISSUE TITLE
Special characters in account login

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/gin-auth#87]
Currently there is no restriction on the characters that can be used at the account login when creating a new account. Login is used in the hierarchical part of various api/account routes, but is not treated as URL encoded which is an error waiting to happen.

Suggestions to solve this are:
- restrict characters when creating the account login to url safe characters
- always base64.RawURL decode the login part of the api/account routes.
- do not use login as part of the hierarchical part of the URL, use URL query instead.

**Comment by gicmo** [comment]
Restricting characters is what most services do I guess. Saves us a lot of trouble too ;)
